/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatIntelliJLaf;
import modelo.Usuario;
import conexionBD.ConexionBD;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JPasswordField;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.UIManager;
import modelo.Usuario;

/**
 *
 * @author Herrera
 */
public class VentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogin
     */
    public static String user = "USUARIO";
    public static String tipo = "EMPLEADO";

    private String[] protips = {
        "al dar clic en una tabla en modo cambio se cargan los datos a los campos del formulario",
        "si das clic en el icono de youtube seras 20% mas feliz, washa nomas lo que puedo hacers",
        "la interfaz genera colores aleatorios a partir de un 30% del circulo cromatico :0",
        "no crees usuarios con espacios en su nombre o pasaran cosas malas (* lo arregla despues)",
        "acepta los terminos y condiciones que estas esperando, de las frases que mas me gustan",
        "si das clic en el icono de github, pos ya de una vez sigueme o no tu sabes jejogs",        
        "desocupa una habitacion antes de reservarla o sino ijuesu pobres clientes",
        "caminar hacia atras es increible deberias intentarlo (es algo imposible al inicio)",
        "chat me recomento la cancion: THE Luminers - Ho Hey, deberias escucharla",
        "anuma se nota que no tengo nada mejor que hacer que escribir mensajes de ayuda que no ayudan a nadie"
    };

    public VentanaLogin() {

        ConexionBD.getConexion();

        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        loginPane = new javax.swing.JPanel();
        txtIniciarSesion = new javax.swing.JLabel();
        btnLogin = new javax.swing.JPanel();
        txtLogin = new javax.swing.JLabel();
        cajaUsuario = new javax.swing.JTextField();
        txtUser = new javax.swing.JLabel();
        cajaPassword = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JLabel();
        userIcon = new javax.swing.JLabel();
        messagePane = new javax.swing.JPanel();
        txtMessageLogin = new javax.swing.JLabel();
        btnCloseMesaggePane = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnReset = new javax.swing.JPanel();
        txtLogin1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        menu = new javax.swing.JPanel();
        btnHomePane = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        txtLogo = new javax.swing.JLabel();
        barra = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        btnMinimize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtTips = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(55, 42, 104));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIniciarSesion.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        txtIniciarSesion.setForeground(new java.awt.Color(100, 100, 100));
        txtIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIniciarSesion.setText("INICIAR SESION");
        loginPane.add(txtIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 440, 30));

        btnLogin.setBackground(new java.awt.Color(52, 156, 244));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(240, 240, 240));
        txtLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLogin.setText("LOGIN");
        btnLogin.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 30));

        loginPane.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 120, 30));

        cajaUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cajaUsuario.setForeground(new java.awt.Color(50, 50, 50));
        cajaUsuario.setMargin(new java.awt.Insets(2, 10, 2, 10));
        loginPane.add(cajaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 280, 30));

        txtUser.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        txtUser.setForeground(new java.awt.Color(50, 50, 50));
        txtUser.setText("username");
        loginPane.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 70, 30));

        cajaPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cajaPassword.setForeground(new java.awt.Color(50, 50, 50));
        cajaPassword.setMargin(new java.awt.Insets(2, 10, 2, 10));
        loginPane.add(cajaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 280, 30));

        txtPassword.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(50, 50, 50));
        txtPassword.setText("password");
        loginPane.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 60, 30));

        userIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario.png"))); // NOI18N
        loginPane.add(userIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 440, -1));

        messagePane.setForeground(new java.awt.Color(33, 235, 103));
        messagePane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        messagePane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messagePaneMouseClicked(evt);
            }
        });
        messagePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMessageLogin.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        txtMessageLogin.setForeground(new java.awt.Color(240, 240, 240));
        txtMessageLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messagePane.add(txtMessageLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 340, 50));

        btnCloseMesaggePane.setFont(new java.awt.Font("bubbleboddy", 0, 18)); // NOI18N
        btnCloseMesaggePane.setForeground(new java.awt.Color(240, 240, 240));
        btnCloseMesaggePane.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCloseMesaggePane.setText("X");
        btnCloseMesaggePane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseMesaggePane.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        messagePane.add(btnCloseMesaggePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 30, 30));

        loginPane.add(messagePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 440, 50));

        jPanel1.setBackground(new java.awt.Color(52, 156, 244));
        loginPane.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 10));

        btnReset.setBackground(new java.awt.Color(0, 153, 153));
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
        });
        btnReset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogin1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        txtLogin1.setForeground(new java.awt.Color(240, 240, 240));
        txtLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLogin1.setText("RESET");
        btnReset.add(txtLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 30));

        loginPane.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 120, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 114, 184));
        jLabel1.setText("¿que estas esperando?");
        loginPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, 20));

        jCheckBox1.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(50, 50, 50));
        jCheckBox1.setText("acepta los terminos y condiciones");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        loginPane.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        bg.add(loginPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 440, 550));

        menu.setBackground(new java.awt.Color(40, 23, 72));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHomePane.setBackground(new java.awt.Color(22, 16, 44));
        btnHomePane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHomePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        menu.add(btnHomePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 260, 50));

        jSeparator1.setBackground(new java.awt.Color(70, 41, 125));
        jSeparator1.setForeground(new java.awt.Color(70, 41, 125));
        jSeparator1.setToolTipText("");
        menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 93, 180, 40));

        txtLogo.setFont(new java.awt.Font("Roboto Cn", 1, 32)); // NOI18N
        txtLogo.setForeground(new java.awt.Color(240, 240, 240));
        txtLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLogo.setText("FASTEL");
        txtLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLogoMouseClicked(evt);
            }
        });
        menu.add(txtLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 140));

        bg.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        barra.setBackground(new java.awt.Color(55, 42, 104));
        barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMouseDragged(evt);
            }
        });
        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMousePressed(evt);
            }
        });
        barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClose.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnClose.setForeground(new java.awt.Color(240, 240, 240));
        btnClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClose.setText("X");
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        barra.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 40, 40));

        btnMinimize.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnMinimize.setForeground(new java.awt.Color(240, 240, 240));
        btnMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMinimize.setText("–");
        btnMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMinimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
        });
        barra.add(btnMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 40, 40));

        bg.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 40));

        jPanel2.setBackground(new java.awt.Color(42, 31, 84));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTips.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        txtTips.setForeground(new java.awt.Color(240, 240, 240));
        txtTips.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTips.setText("al dar clic en una tabla en modo cambio se cargan los datos a los campos del formulario");
        txtTips.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtTips.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTipsMouseClicked(evt);
            }
        });
        jPanel2.add(txtTips, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 780, 50));

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 670, 1020, 50));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int xMouse, yMouse;
    private void barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_barraMouseDragged

    private void barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barraMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_barraMousePressed

    Usuario usuario = new Usuario();

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        char[] arrayC = cajaPassword.getPassword();
        String pass = new String(arrayC);

        if (!cajaUsuario.getText().trim().equals("") && !pass.trim().equals("")) {
            usuario.setUsuario(cajaUsuario.getText());
            usuario.setPassword(pass);
            ResultSet rs = ConexionBD.verificarUsuario(usuario);

            try {
                rs.next();
                if (rs.getString(1) != null) {

                    String[] datos = rs.getString(1).split(" ");

                    user = datos[0].toUpperCase();
                    tipo = datos[1].toUpperCase();

                    System.out.println(user);
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            new VentanaPrincipal().setVisible(true);
                        }
                    });
                    dispose();
                } else {
                    messagePane.setBackground(new Color(219, 0, 84));
                    txtMessageLogin.setText("DATOS ERRONEOS intenta de nuevo");
                    messagePane.setVisible(true);
                    shake(VentanaLogin.this);
                }

            } catch (SQLException e1) {
                e1.printStackTrace();
            }

        } else {
            String noDatos = "Introduce [";

            if (cajaUsuario.getText().trim().equals("")) {
                noDatos += " USUARIO";
            }

            if (pass.trim().equals("")) {
                noDatos += " PASSWORD";
            }

            noDatos += " ]";

            messagePane.setBackground(new Color(219, 0, 84));
            txtMessageLogin.setText(noDatos);
            messagePane.setVisible(true);
            shake(VentanaLogin.this);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void messagePaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messagePaneMouseClicked
        messagePane.setVisible(false);
    }//GEN-LAST:event_messagePaneMouseClicked

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        restablecerComponentes(cajaUsuario, cajaPassword);
    }//GEN-LAST:event_btnResetMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void txtLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLogoMouseClicked

    }//GEN-LAST:event_txtLogoMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setExtendedState(ICONIFIED);
        this.setExtendedState(1);
    }//GEN-LAST:event_btnMinimizeMouseClicked
    int indiceActual = 0;
    private void txtTipsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTipsMouseClicked
        indiceActual++;
        if (indiceActual == protips.length) {
            indiceActual = 0;
        }
        txtTips.setText(protips[indiceActual]);
    }//GEN-LAST:event_txtTipsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    UIManager.setLookAndFeel(new FlatIntelliJLaf());
                } catch (Exception e) {
                    e.printStackTrace();
                }
                new VentanaLogin().setVisible(true);
            }
        });
    }

    public void restablecerComponentes(JComponent... componentes) {
        for (JComponent c : componentes) {

            if (c instanceof JTextField) {
                ((JTextField) c).setText("");
            } else if (c instanceof JCheckBox) {
                ((JCheckBox) c).setSelected(false);
            } else if (c instanceof JComboBox) {
                ((JComboBox) c).setSelectedIndex(0);
            } else if (c instanceof JSpinner) {
                ((JSpinner) c).setValue(0);
            } else if (c instanceof JPasswordField) {
                ((JPasswordField) c).setText("");
            }
        }
    }

    public static void shake(JFrame frame) {
        int originalX = frame.getLocation().x;
        int originalY = frame.getLocation().y;
        final int SHAKE_DISTANCE = 3;
        final int SHAKE_DURATION = 250; // en milisegundos
        final int SHAKE_FREQUENCY = 25; // en milisegundos
        final long endTime = System.currentTimeMillis() + SHAKE_DURATION;

        Thread t = new Thread(() -> {
            while (System.currentTimeMillis() < endTime) {
                try {
                    frame.setLocation(originalX + (int) (Math.random() * SHAKE_DISTANCE * 2) - SHAKE_DISTANCE,
                            originalY + (int) (Math.random() * SHAKE_DISTANCE * 2) - SHAKE_DISTANCE);
                    Thread.sleep(SHAKE_FREQUENCY);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
            frame.setLocation(originalX, originalY);
        });
        t.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnCloseMesaggePane;
    private javax.swing.JPanel btnHomePane;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JLabel btnMinimize;
    private javax.swing.JPanel btnReset;
    private javax.swing.JPasswordField cajaPassword;
    private javax.swing.JTextField cajaUsuario;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel loginPane;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel messagePane;
    private javax.swing.JLabel txtIniciarSesion;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtLogin1;
    private javax.swing.JLabel txtLogo;
    private javax.swing.JLabel txtMessageLogin;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtTips;
    private javax.swing.JLabel txtUser;
    private javax.swing.JLabel userIcon;
    // End of variables declaration//GEN-END:variables
}
